module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    //'subject-case': [2, 'always', 'lower-case'],
    'subject-case': [0],
    'scope-case': [2, 'always', 'kebab-case'],
    'scope-min-length': [2, 'always', 2],
    'header-max-length': [2, 'always', 100],
    'scope-enum': [
      2,
      'always',
      [
        // Estándar
        'tokens',
        'components',
        'hooks',
        'utils',
        'styles',
        'layout',
        'theme',
        'seo',
        'assets',
        'test',
        'workflow',
        'config',
        'deps',
        // Dependabot legacy (dev-deps); nuevos PRs usan chore(deps): vía .github/dependabot.yml
        'deps-dev',
        'readme',
        'gitflow',
        'build',
        'ci',
        'release',
        // Secciones portfolio
        'hero',
        'header',
        'about',
        'projects',
        'contact',
        'footer',
        'skills',
      ],
    ],
  },
}
