export { AboutBio } from './AboutBio'
export { AboutValues } from './AboutValues'
export { AboutSkills } from './AboutSkills'
export { AboutExperience } from './AboutExperience'
export { AboutAcademic } from './AboutAcademic'
export { AboutCerts } from './AboutCerts'
export { SectionLabel } from '@/shared/components/SectionLabel'
